### PR TITLE
Reset the cache of the last modified key when the form data is reset or updated externally

### PR DESCRIPTION
**Pull request by atf-cguerin**
This is the same patch proposed as a fix for https://github.com/aldeed/meteor-autoform/issues/1599 converted into a pull request after a little more internal testing, in case it can simplify the merging process if it's approved.

### CODE REVIEW

**Comment by Pagebakers** [comment]
When can we expect this to be merged?

This has been an issues for a couple of years already where change events of inputs (select/radio) aren't triggered after updating the form sourceDoc.

**Comment by Pagebakers** [comment]
We could also bind the keyVal to the docId if it's available

```javascript
keyVal = key + '___' + keyVal;

if (this.docId) {
keyVal = this.docId + '___' + keyVal
}
if (formId in lastKeyVals && keyVal === lastKeyVals[formId]) {
      return;
    }
```

**Comment by velatinicolas** [comment]
Hello @jankapunkt, I and my work team are currently facing the same issue as described above, and we eventually stumbled upon this pull request which seems to perfectly fix the bug. Do you have any explanation on why it has not been merged? Would it be conceivable to merge it now, even if it has been closed 2 years ago?

**Comment by jankapunkt** [comment]
@velatinicolas I think it has been closed due to being stale for a long time and at that time I was not able to review all PRs. Feel free to reopen and assign me for review, today I will have some time for OS dev 😀

**Comment by jankapunkt** [comment]
@velatinicolas okay I now know why I closed, mainly because it introduces a global-scoped variable which is nowadays considered an anti-pattern.

I could extend the PR by rewriting this to be within the `AutoForm` namespace:

```js
AutoForm._lastKeyVals = {}
```

wdyt?

**Comment by velatinicolas** [comment]
First of all, thanks for your quick answers and propositions! :rocket:

I agree, the global variable bothered me a bit as well. Including it in the `AutoForm` namespace looks great.

But actually, after some tests I made today, for our needs we'd only need to do the fix in the `autoform-events.js` file, because our problem occurs on a form reset. I've not been able to reproduce the bug initially described in the issue https://github.com/Meteor-Community-Packages/meteor-autoform/issues/1599.

As you are the maintainer of this project, I'll let you decide on this. Either we apply the fix in both `autoform-events.js` and `autoForm.js` file, therefore requiring the rework with the namespace ; or we keep the `lastKeyVals` variable declared with `const` and only fix `autoform-events.js`.

**Comment by velatinicolas** [comment]
Thanks for the merge @jankapunkt :rocket:

**Pull request merged**
